/**************************************************************************
 * Copyright (c) 2011-2013 Anya Helene Bagge
 * Copyright (c) 2011-2013 University of Bergen
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version. See http://www.gnu.org/licenses/
 * 
 * 
 * See the file COPYRIGHT for more information.
 * 
 * Contributors:
 * * Anya Helene Bagge
 * 
 *************************************************************************/
package org.nuthatchery.pica.parsergen;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.net.URI;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

import org.eclipse.core.resources.IFile;
import org.eclipse.imp.pdb.facts.IConstructor;
import org.eclipse.imp.pdb.facts.IString;
import org.eclipse.imp.pdb.facts.ITuple;
import org.eclipse.imp.pdb.facts.IValue;
import org.eclipse.imp.pdb.facts.io.BinaryValueReader;
import org.eclipse.imp.pdb.facts.io.BinaryValueWriter;
import org.nuthatchery.pica.ConsolePicaInfra;
import org.nuthatchery.pica.Pica;
import org.nuthatchery.pica.resources.ILanguage;
import org.nuthatchery.pica.resources.IManagedPackage;
import org.nuthatchery.pica.resources.IResourceManager;
import org.nuthatchery.pica.resources.IWorkspaceConfig;
import org.nuthatchery.pica.resources.storage.IStorage;
import org.nuthatchery.pica.terms.TermFactory;
import org.rascalmpl.interpreter.Evaluator;

public class GenerateAuxFiles {
	private final String moduleName;
	private String outDir;
	private String baseName;
	private String srcDir;


	GenerateAuxFiles(String baseName, String srcDir, String outDir) {
		this.baseName = baseName;
		this.outDir = outDir;
		this.srcDir = srcDir;
		this.moduleName = baseName.replace(File.separator, "::");

	}


	private String getFileName(String dir, String name, String suffix) {
		String fileName = dir + File.separator + name + suffix;
		System.err.println("Filename: " + fileName);
		return fileName;
	}


	private IConstructor loadGrammar(Evaluator eval) throws IOException {
		ITuple tuple = (ITuple) BinaryValueReader.readValueFromFile(eval.getValueFactory(), eval.getCurrentEnvt().getStore(), new File(getFileName(srcDir, baseName, "Grammar.pbf")));
		return (IConstructor) tuple.get(1);
	}


	private void saveAstModule(IValue str) throws IOException {
		String astModule = "module " + moduleName + "AST\n" + ((IString) str).getValue();

		String outFile = getFileName(outDir, baseName, "AST.rsc");

		try (PrintStream stream = new PrintStream(new FileOutputStream(outFile), false, "UTF-8")) {
			stream.print(astModule);
		}
	}


	private void saveGrammarInfo(IValue info) throws IOException {

		String outFile = getFileName(outDir, baseName, "Info.pbf");
		try (OutputStream stream = new FileOutputStream(outFile)) {
			new BinaryValueWriter().write(info, stream, TermFactory.ts);
		}
	}


	private void savePPModule(IValue str) throws IOException {
		String ppModule = "// WARNING: this file is autogenerated! just copy it and adapt to your needs\n" //
				+ "module " + moduleName + "PP\n" //
				+ "import org::magnolialang::pgf::Token;\n" //
				+ "import org::magnolialang::pgf::Stream;\n" //
				+ "import org::magnolialang::pgf::AstToStream;\n" //
				+ "import " + moduleName + "AST;\n" //
				+ "public default Stream[Token] pp(AST ast, Stream[Token] stream) {\n" //
				+ "  return stream;\n" //
				+ "}\n" //
				+ ((IString) str).getValue();

		String outFile = getFileName(outDir, baseName, "PP.rsc");

		try (PrintStream stream = new PrintStream(new FileOutputStream(outFile), false, "UTF-8")) {
			stream.print(ppModule);
		}
	}


	protected void generate() throws IOException {
		Evaluator eval = Pica.get().getEvaluatorFactory().makeEvaluator();
		eval.doImport(null, "org::magnolialang::parsergen::GrammarInfoGenerator");
		IConstructor grammar = loadGrammar(eval);

		ITuple infoTuple = (ITuple) eval.call("grammar2info", grammar);

		saveGrammarInfo(infoTuple.get(0));
		saveAstModule(infoTuple.get(1));
		savePPModule(infoTuple.get(2));
	}


	public static void main(String[] args) throws IOException {
		if(args.length != 3) {
			System.err.println("Usage: java org.nuthatchery.pica.parsergen.GenerateParser <basename> <input_dir/> <output_dir/>");
			System.exit(1);
		}

		Pica.set(new ConsolePicaInfra(new IWorkspaceConfig() {

			@Override
			public Collection<String> getActiveNatures() {
				return Collections.EMPTY_LIST;
			}


			@Override
			public ClassLoader getParserClassLoader() {
				// TODO Auto-generated method stub
				return null;
			}


			@Override
			public void initCompiler() {
			}


			@Override
			public IManagedPackage makePackage(IResourceManager manager, IFile resource, IStorage storage, IConstructor id, ILanguage lang) {
				return null;
			}


			@Override
			public String moreRascalClassPath() {
				return null;
			}


			@Override
			public List<URI> moreRascalSearchPath() {
				return null;
			}

		}));
		GenerateAuxFiles generator = new GenerateAuxFiles(args[0], args[1], args[2]);
		generator.generate();
	}

}
